version: '3'
services:
  postgres:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=track_data
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    restart: always
    build: .
    container_name: test_task
    ports:
      - 5473:80
    volumes:
      - .:/app
    depends_on:
    - postgres
    entrypoint: ["python", "app.py"]